projectType: extension
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11 # TODO: Remove -DruntimeVersion=4.7.4 once Mule Runtime 4.9.3 is working with JDK 11
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DminVersion=4.3.0 -DruntimeVersion=4.7.4
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0
