projectType: extension
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
    # In jdk11 configurations, the runtime is set to 4.8.x until W-17842670 is fixed
    # Because of this, the discovery configuration is bypassed and we need to specify runtimeProduct as MULE_EE
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DruntimeVersion=4.8.5 -DruntimeProduct=MULE_EE
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0
